<?php

/**
 * Danh mục trợ cấp tháng — mirror sheet lương BestPacific (cột I–Z).
 * breakdown_key → key trong payroll_results.breakdown / phiếu BPVN.
 */
return [
    'catalog' => [
        'allowance_position' => [
            'label' => 'Trợ cấp CV',
            'label_cn' => '岗位补贴',
            'excel_column' => 'I',
            'breakdown_key' => 'allowance_position',
            'taxable' => true,
            'counts_in_gross' => true,
        ],
        'allowance_other' => [
            'label' => 'Trợ cấp khác',
            'label_cn' => '其他',
            'excel_column' => 'J',
            'breakdown_key' => 'allowance_other',
            'taxable' => true,
            'counts_in_gross' => true,
        ],
        'allowance_phone' => [
            'label' => 'Điện thoại',
            'label_cn' => '电话',
            'excel_column' => 'K',
            'breakdown_key' => 'allowance_phone',
            'taxable' => true,
            'counts_in_gross' => true,
        ],
        'allowance_living' => [
            'label' => 'Hỗ trợ khó khăn sinh hoạt',
            'label_cn' => '生活补贴',
            'excel_column' => 'L',
            'breakdown_key' => 'allowance_living',
            'taxable' => true,
            'counts_in_gross' => true,
        ],
        'allowance_housing' => [
            'label' => 'Hỗ trợ nhà ở',
            'label_cn' => '住宿补贴',
            'excel_column' => 'M',
            'breakdown_key' => 'allowance_housing',
            'taxable' => true,
            'counts_in_gross' => true,
        ],
        'allowance_petrol' => [
            'label' => 'Hỗ trợ xăng xe',
            'label_cn' => '油费补贴',
            'excel_column' => 'N',
            'breakdown_key' => 'allowance_petrol',
            'taxable' => true,
            'counts_in_gross' => true,
        ],
        'allowance_meal' => [
            'label' => 'Bồi dưỡng ăn ca',
            'label_cn' => '餐费补贴',
            'excel_column' => 'O',
            'breakdown_key' => 'allowance_meal',
            'taxable' => true,
            'counts_in_gross' => true,
        ],
        'allowance_environment' => [
            'label' => 'Trợ cấp môi trường (T6–T10)',
            'label_cn' => '茶凉补贴',
            'excel_column' => 'P',
            'breakdown_key' => 'allowance_environment',
            'taxable' => true,
            'counts_in_gross' => true,
            'active_months' => [6, 7, 8, 9, 10],
        ],
        'allowance_housing_distance' => [
            'label' => 'Hỗ trợ nhà trọ (>30km)',
            'label_cn' => '住宿补贴(30km)',
            'excel_column' => 'Q',
            'breakdown_key' => 'allowance_housing_distance',
            'taxable' => true,
            'counts_in_gross' => true,
        ],
        'allowance_probation_insurance' => [
            'label' => 'BHXH/BHYT/BHTN Cty trả (thử việc)',
            'label_cn' => '试用保险',
            'excel_column' => 'T',
            'breakdown_key' => 'allowance_probation_insurance',
            'taxable' => false,
            'counts_in_gross' => false,
        ],
        'allowance_childcare' => [
            'label' => 'Hỗ trợ gửi trẻ (<72 tháng)',
            'label_cn' => '育儿',
            'excel_column' => 'U',
            'breakdown_key' => 'allowance_childcare',
            'taxable' => true,
            'counts_in_gross' => true,
        ],
        'allowance_firefighting' => [
            'label' => 'Trợ cấp PCCC',
            'label_cn' => '消防',
            'excel_column' => 'V',
            'breakdown_key' => 'allowance_firefighting',
            'taxable' => true,
            'counts_in_gross' => true,
        ],
        'allowance_safety' => [
            'label' => 'Trợ cấp an ninh vệ sinh',
            'label_cn' => '安全卫生',
            'excel_column' => 'W',
            'breakdown_key' => 'allowance_safety',
            'taxable' => true,
            'counts_in_gross' => true,
        ],
        'allowance_community' => [
            'label' => 'Hỗ trợ cộng viên',
            'label_cn' => '员工互助',
            'excel_column' => 'X',
            'breakdown_key' => 'allowance_community',
            'taxable' => true,
            'counts_in_gross' => true,
        ],
        'allowance_trip_housing' => [
            'label' => 'Hỗ trợ nhà ở đi công tác',
            'label_cn' => '出差住宿',
            'excel_column' => 'Y',
            'breakdown_key' => 'allowance_trip_housing',
            'taxable' => true,
            'counts_in_gross' => true,
        ],
        'allowance_health_check' => [
            'label' => 'Hỗ trợ phí khám sức khỏe nhân việc',
            'label_cn' => '体检',
            'excel_column' => 'Z',
            'breakdown_key' => 'allowance_health_check',
            'taxable' => true,
            'counts_in_gross' => true,
        ],
        'allowance_sales_commission' => [
            'label' => 'Thưởng doanh số',
            'label_cn' => '销售提成',
            'breakdown_key' => 'allowance_sales_commission',
            'taxable' => true,
            'counts_in_gross' => false,
        ],
        'incentive_bonus' => [
            'label' => 'Thưởng khuyến khích CNV ổn định công việc',
            'label_cn' => '稳定奖',
            'excel_column' => 'AA',
            'breakdown_key' => 'incentive_bonus',
            'taxable' => true,
            'counts_in_gross' => true,
        ],
    ],

    'travel_support_key' => 'travel_support',
];
